### ISSUE TITLE
Comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [julia1512/ProyectoFinalBioinf2017-II-JCSZ#1]
Me parece bien el planteamiento de tu proyecto. Solo tengo una pregunta ¿con qué software/paquete piensas hacer los análisis? ¿ya lo tienes pensado?

**Comment by julia1512** [comment]
Había pensado utilizar primero PLINK para los estadísticos de los SNPs. Para el análisis de la estructura poblacional a partir de los marcadores de ancestría informativos pensaba utilizar el paquete snpMatrix de bioconductor o el software EIGENSTRAT. Por último para los análisis de asociación pensaba hacerlos en R mediante regresiones lineales y posiblemente algún tipo de análisis multivariado dependiendo del los datos que vaya sacando.

**Comment by AliciaMstt** [comment]
Ok, suena bien. Checa tmb SNPstats de bioconductor.
